### PR TITLE
Revert "Revert "Run on Elixir 1.15 and Erlang 26""

### PR DESCRIPTION
**Pull request by neenjaw**
Reverts exercism/elixir-test-runner#110

---

Context: Some production deployment detail prevented the test runner from functioning properly.  Rather than gate the whole track with a failure, @iHiD and I chose to revert the recent upgrade.

This PR contains the original changes.

@angelikatyborska, @dabaer I'll assign this to you for now.  @iHiD and @ErikSchierboom will provide logs later this week to investigate.

---

edit:

@dabaer found that one change in 1.15 was that compiler output was now being reported via stderr rather than stdout.  An early decision was made to only capture stdout.

Solve by @dabaer: redirect stderr to stdout

### CODE REVIEW

**Comment by dabaer** [comment]
Interesting, 1.15 is the update that keeps on breaking I suppose. I published https://exercism.org/tracks/elixir/exercises/armstrong-numbers/solutions/dbaer about 3 hours before that forum post on the issue, but the solution didn't have a compile error to expose the issue.

I'll fiddle with this locally to try and reproduce

**Comment by neenjaw** [comment]
Yea, I think we'll have to wait for the logs from @ErikSchierboom later this week to know what happened here.

**Comment by dabaer** [comment]
@neenjaw so it looks like errors in Elixir 1.15 are being written to `sterr` instead of `stdout` now which doesn't seem to be captured with `${}` as we do here:

https://github.com/exercism/elixir-test-runner/blob/21c1ba883dccce3c0c5a0e82a76478386cbb368f/bin/run.sh#L46

Redirecting `stderr` to `stdout` as below fixes the issue:

```bash
compile_step=$(MIX_ENV=test mix compile 2>&1)
```

**Comment by neenjaw** [comment]
Nice find. 

Can we add a docker integration test case which has a compilation failure and assert the output file to contain the compilation error?

**Comment by dabaer** [comment]
I don't seem to be able to push to this branch, do I need to be assigned?

**Comment by neenjaw** [comment]
Assigned now, does that work? If not it is likely a permissions issue -- can either make changes and post a patch I can apply or make a new branch in your fork, reset to this branch's head, commit your changes.  Whichever is more convenient for you.

**Comment by dabaer** [comment]
Should I make a new PR for it, or is there some way to fold it in here?

https://github.com/dabaer/elixir-test-runner/commit/9fdb8a9265bb231d86f54b523345d1407a4413aa

**Comment by neenjaw** [comment]
Cherry picked your commit

**Review by angelikatyborska — APPROVED** [review]
I'm clicking approve without reading just so that @neenjaw has the power to merge

**Comment by neenjaw** [comment]
@dabaer here we go!

**Comment by dabaer** [comment]
Looks to be working fine

image

**Pull request merged**
