### PR TITLE
Smoke tests against *all* exercises

### LINKED ISSUE #72: Smoke tests against *all* exercises
As we learned in https://github.com/exercism/elixir/issues/1014 the test runner has bugs that cause it to be unable to ever pass the tests for two specific exercises. It would be great if we had an automated way of detecting this. Currently we have a few manually set up smoke tests for 5 different exercises. To make it possible for all exercises, it would have to be automated, based on a git submodule of the [exercism/elixir](https://github.com/exercism/elixir/) repo.

It would be enough to test each exercise and its exemplar/example solution and assert that the test runner produces a positive result within the time limit (I'm not sure at the moment what the time limit is). It doesn't even need to happen for every PR, maybe just on `main` or only when pushing a new docker image.

### PR DESCRIPTION
**Pull request by jiegillet**
Closes #72.

This PR adds smoke tests against all exercises via a submodule and also fixes two tests that were failing. 
Those fixes are terrible hacks with side effects fixed by hacks and I cannot wait for 1.13 to come out ^^

The new shell script is a modified version of the script from `elixir` that tests all solutions. Removing the `set -euo pipefail` produces a better error message in case of failure (but then doesn't fail fast).

### CODE REVIEW

**Review by angelikatyborska — APPROVED** [review]
I didn't do a detailed review, just a sanity check, but everything looks alright to me. Let's get the fix deployed.

>  Removing the set -euo pipefail produces a better error message in case of failure (but then doesn't fail fast).

With `set -euo pipefail`, I got literally no hints (it just said `Testing: forth %` and then exited with code 1), so I'm in favor of removing it.

**Comment by jiegillet** [comment]
> With `set -euo pipefail`, I got literally no hints (it just said `Testing: forth %` and then exited with code 1), so I'm in favor of removing it.

Yes, that's the point of `-e` it exists the script as soon as a command exits with 1, you can't show the failure message. It makes sense for CI in order not to waste computations, but honestly whenever a test doesn't pass it's often not just one exercise that fails and we end up running it many more times, especially if there is no error message.

I commented it out. I also checked that the script does exit with code 1 even if it doesn't exit early.

I copied it from `elixir`, maybe I should remove it over there as well? It has made debugging harder in the past several times.

**Comment by neenjaw** [comment]
> I commented it out. I also checked that the script does exit with code 1 even if it doesn't exit early.
> 
> I copied it from `elixir`, maybe I should remove it over there as well? It has made debugging harder in the past several times.

Why didn't you rather add `set +e` and `set -e` around the test command? The use of `-e` makes the script safer to run.

**Comment by jiegillet** [comment]
I suppose I could have done that yes, but given that the tests commands are the very core of the script, this seemed simpler. 
Probably another reason is that my bash knowledge isn't that good. Do you think we should fix it?

**Comment by neenjaw** [comment]
My view on bash scripts is just that we should fail gracefully, quickly, and determinately if the script is wandering off its happy path.    Using `set -euo pipefail` forces us to make choose when to ignore error exit codes (like in the case of `mix test`) rather ignoring all of them.  While that may be pedantic, when a shell script is run it is given a lot of leeway by the system, so we should be as careful with it as possible.  My suggestion is to replace the `set -euo pipefail` and wrap just the parts where the exit code shouldn't influence the run status of the script with `set +e; set -e` as that is a better shell scripting practice.

**Comment by jiegillet** [comment]
Thank you very much for your intervention. I always learn a lot from your advice :)

**Pull request merged**
